### ISSUE TITLE
File "long_description.txt" missing

### ISSUE THREAD

**Issue by jgm315** [ludvikalkhoury/PyGrabIt#1]
Hello,

Great project!

The file "long_description.txt" is missing in the repo, which crashed the install script via setup.py.

I'm referring to the file in line 20 of "/setup.py":

`long_description = (HERE2 / "long_description.txt").read_text()`

Cheers.

**Comment by ludvikalkhoury** [comment]
Hello, 
Thank you for bringing this to my attention. 
I have added the missing file ("long_description.txt") to the repo. 

Thanks,
Ludvik

**Comment by ludvikalkhoury** [comment]
Hello, 
Thank you for bringing this to my attention. 
I have added the missing file ("long_description.txt") to the repo. 

Thanks,
Ludvik
